common/models/Event.php
<?php

namespace common\models;

use Yii;
use yii\db\ActiveRecord;
use yii\helpers\Json;

/**
 * This is the model class for table "event".
 *
 * @property integer $id
 * @property integer $type
 * @property integer $target
 * @property integer $importance
 * @property string $text
 * @property string $data
 * @property integer $created
 * @property integer $informed
 */
class Event extends ActiveRecord
{
    const IMPORTANCE_LOW = 1;
    const IMPORTANCE_NORMAL = 5;
    const IMPORTANCE_HIGH = 10;

    const TYPE_COMPLETE_THERAPY = 1;
    const TYPE_NEED_MODERATION = 2;
    const TYPE_PAYMENT_ERROR = 3;
    const TYPE_APPOINTMENT = 4;
    const TYPE_CLIENT = 5;
    const TYPE_CHANGE_TIMEZONE = 6;

    const STATUS_INFORMED = 1;
    const STATUS_NOT_INFORMED = 0;

    const RECEIVER_USER = 1;
    const RECEIVER_ADMIN = 0;
    
    protected $_data;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'event';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['type', 'importance', 'data'], 'required'],
            [['type', 'importance', 'created', 'informed', 'target'], 'integer'],
            [['text', 'data'], 'string']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('main', 'ID'),
            'type' => Yii::t('main', 'Type'),
            'target' => Yii::t('main', 'Target'),
            'importance' => Yii::t('main', 'Importance'),
            'text' => Yii::t('main', 'Text'),
            'data' => Yii::t('main', 'Data'),
            'created' => Yii::t('main', 'Created'),
            'informed' => Yii::t('main', 'Informed')
        ];
    }

    /**
     * @return array
     */
    public function behaviors()
    {
        return [
            'timestamp' => [
                'class' => 'yii\behaviors\TimestampBehavior',
                'attributes' => [
                    ActiveRecord::EVENT_BEFORE_INSERT => ['created'],
                ],
            ],
        ];
    }

    /**
     * @param array $row
     * @return AppointmentEvent|ChangeTimezoneEvent|ClientEvent|CompleteTherapyEvent|Event|NeedModerationEvent|PaymentErrorEvent
     */
    public static function instantiate($row)
    {
        switch ($row['type']) {
            case self::TYPE_COMPLETE_THERAPY:
                return new CompleteTherapyEvent();
            case self::TYPE_NEED_MODERATION:
                return new NeedModerationEvent();
            case self::TYPE_PAYMENT_ERROR:
                return new PaymentErrorEvent();
            case self::TYPE_APPOINTMENT:
                return new AppointmentEvent();
            case self::TYPE_CLIENT:
                return new ClientEvent();
            case self::TYPE_CHANGE_TIMEZONE:
                return new ChangeTimezoneEvent();
            default:
                return new self;
        }
    }

    /**
     * After find
     */
    public function afterFind()
    {
        parent::afterFind();

        $this->_data = Json::decode($this->data);
    }

    /**
     * @return array
     */
    public function getTypes()
    {
        return [
            self::TYPE_COMPLETE_THERAPY => Yii::t('main', 'Completed therapy'),
            self::TYPE_NEED_MODERATION => Yii::t('main', 'Need moderation'),
            self::TYPE_PAYMENT_ERROR => Yii::t('main', 'Errors while payment settle'),
            self::TYPE_CLIENT => Yii::t('main', 'Client events'),
            self::TYPE_APPOINTMENT => Yii::t('main', 'Appointment events'),
            self::TYPE_CHANGE_TIMEZONE => Yii::t('main', 'Changed timezone events')
        ];
    }

    /**
     * @return mixed
     */
    public function getTypeName()
    {
        $types = $this->getTypes();
        return $types[$this->type];
    }

    /**
     * @return array
     */
    public function getImportanceLevels()
    {
        return [
            self::IMPORTANCE_LOW => Yii::t('main', 'Low'),
            self::IMPORTANCE_NORMAL => Yii::t('main', 'Normal'),
            self::IMPORTANCE_HIGH => Yii::t('main', 'High'),
        ];
    }

    /**
     * @return array
     */
    public function getImportanceIcon()
    {
        return [
            self::IMPORTANCE_LOW => '<span class="label label-success"><i class="fa fa-exclamation"></i><span>',
            self::IMPORTANCE_NORMAL => '<span class="label label-warning"><i class="fa fa-exclamation"></i><span>',
            self::IMPORTANCE_HIGH => '<span class="label label-danger"><i class="fa fa-exclamation"></i><span>',
        ];
    }

    /**
     * @return string
     */
    public function getAlias()
    {
        return 'event';
    }

    /**
     * @return mixed
     */
    public function getData()
    {
        return $this->_data;
    }

    /**
     * Set informed
     */
    public function setInformed()
    {
        $this->informed = self::STATUS_INFORMED;
        $this->save(false);
    }
}

common/models/Profile.php
<?php

namespace common\models;

use Yii;
use common\components\UploadedFileBehavior;
use yii\db\ActiveQuery;
use yii\db\ActiveRecord;

/**
 * This is the model class for table "profile".
 *
 * @property integer $id
 * @property integer $user_id
 * @property string $name
 * @property string $image
 * @property boolean $agree_mailing
 * @property string $birth_date
 * @property string $rec_token
 * @property string $type
 * @property boolean $show_tooltips
 */
class Profile extends ActiveRecord
{
    public $imageFile;

    const TYPE = 'user';
    const MAX_IMAGE_SIZE = 1048576; //1mb

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'profile';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => UploadedFileBehavior::className(),
                'subdirectoryName' => self::TYPE,
                'defaultImage' => 'default-user.jpg',
                'attributes' => $this->getImageAttributes(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name'], 'requiredName'],
            [['user_id', 'number', 'hide_age'], 'integer'],
            [['alias', 'name', 'type'], 'string', 'max' => 255],
            [['image'], 'string', 'max' => 255],
            [['agree_mailing', 'show_tooltips'], 'boolean'],
            [['agree_mailing', 'show_tooltips'], 'default', 'value' => true],
            [['imageFile'], 'file', 'extensions' => 'jpg, gif, png'],
        ];
    }

    /**
     * @param $attribute
     * @param $params
     */
    public function requiredName($attribute, $params)
    {
        if ($this->name == null && $this->type == 'user') {
            $this->addError($attribute, Yii::t('backend', 'Name is required'));
        }
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'name' => Yii::t('main', 'Name'),
            'image' => Yii::t('backend', 'Image'),
            'imageFile' => Yii::t('backend', 'Image'),
        ];
    }

    /**
     * @param array $row
     * @return Profile|Therapist
     */
    public static function instantiate($row)
    {
        switch ($row['type']) {
            case Therapist::TYPE:
                return new Therapist();
            default:
                return new self;
        }
    }

    /**
     * @return bool
     */
    public function beforeDelete()
    {
        $this->deleteMediaFile('image');

        return parent::beforeDelete();
    }

    /**
     * @return bool
     */
    public function isTherapist()
    {
        return $this->type === Therapist::TYPE;
    }

    /**
     * @return ActiveQuery
     */
    public function getAdditional()
    {
        return $this->hasOne(TherapistAdditional::className(), ['user_id' => 'user_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'user_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBots()
    {
        return $this->hasMany(UserBots::className(), ['user_id' => 'user_id']);
    }

    /**
     * @return array
     */
    public function getImageAttributes()
    {
        return [
            'image' => [
                'fileAttribute' => 'imageFile',
                'width' => 128,
                'height' => 128
            ],
        ];
    }

    /**
     * @param bool $insert
     * @return bool
     */
    public function beforeSave($insert)
    {
        if ($insert && empty($this->alias)) {
            $this->alias = self::getUniqueAlias();
        }
        return parent::beforeSave($insert);
    }

    /**
     * @param int $length
     * @return string
     */
    public static function getUniqueAlias($length = 20)
    {
        $randomString = Yii::$app->getSecurity()->generateRandomString($length);
        if (!self::findOne(['alias' => $randomString])) {
            return $randomString;
        }

        return self::generateUniqueRandomString($length);
    }

    /**
     * @return bool
     */
    public function isPseudoTherapist()
    {
        return false;
    }

    /**
     * Is profile user deleted
     * @return bool
     */
    public function isDeleted()
    {
        return empty($this->user) || $this->user->isDeleted();
    }

    /**
     * @return bool
     */
    public function isProfileImageSocial()
    {
        if (substr($this->image, 0, 7) === 'http://') {
            return true;
        }

        if (substr($this->image, 0, 8) === 'https://') {
            return true;
        }

        return false;
    }

    /**
     * @return int|string
     */
    public function getPaidAppointmentsCount()
    {
        return Appointment::find()
            ->where(['user_id' => $this->user_id])
            ->andWhere(['payment_status' => Appointment::PAID])
            ->count();
    }
}

backend/controllers/SiteController.php
<?php

namespace backend\controllers;

use common\components\ConsoleHelper;
use common\models\LoginForm;
use common\models\Page;
use Yii;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\web\Controller;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout', 'index', 'migrate', 'links'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * @return string|\yii\web\Response
     */
    public function actionLogin()
    {
        if (!\Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }

        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * @return \yii\web\Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * @return bool
     */
    public function actionMigrate()
    {
        return ConsoleHelper::runConsoleActionFromWebApp('migrate', ['migrationPath' => '@console/migrations/', 'interactive' => false]);
    }

    /**
     * @return array
     */
    public function actionLinks()
    {
        Yii::$app->response->format = 'json';
        $links[] = [
            'name' => Yii::t('backend', 'Select page') . '...',
            'url' => ''
        ];

        $pages = Page::find()->with('translation')->all();
        foreach ($pages as $page) {
            $links[] = [
                'name' => $page->name . ' (' . $page->getTypeName() . ')',
                'url' => $page->getUrl()
            ];
        }

        return $links;
    }
}

frontend/controllers/SiteController.php
<?php

namespace frontend\controllers;

use common\components\SiteManager;
use common\models\Therapist;
use common\models\TherapistReview;
use frontend\components\FrontendController;
use frontend\components\PageBehavior;
use Yii;
use yii\data\ActiveDataProvider;
use yii\db\Expression;
use yii\elasticsearch\Query;
use yii\web\Cookie;

/**
 * Class SiteController
 * @package frontend\controllers
 */
class SiteController extends FrontendController
{
    /**
     * @return array
     */
    public function behaviors()
    {
        return [
            [
                'class' => PageBehavior::className(),
                'section' => 'home'
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
            ],
        ];
    }

    /**
     * @param \yii\base\Action $event
     * @return bool
     */
    public function beforeAction($event)
    {
        if ($this->action->id === 'subscribe-success') {
            \Yii::$app->controller->enableCsrfValidation = false;
        }
        return parent::beforeAction($event);
    }

    /**
     * @return string
     */
    public function actionIndex()
    {
        $businessCardTherapists = Therapist::find()
            ->where(['is not', 'business_card_url', null])
            ->andWhere(['!=', 'business_card_url', ''])
            ->all();

        foreach ($businessCardTherapists as $therapist) {
            /** @var Therapist $therapist */
            $therapist->business_card_url = str_replace('?autoplay=1', '', $therapist->business_card_url);
        }

        $therapistReviews = TherapistReview::find()
            ->with('therapist')
            ->where(['published' => TherapistReview::STATUS_PUBLISHED])
            ->orderBy(new Expression('RAND()'))
            ->limit(20)
            ->all();

        return $this->render('index', [
            'businessCardTherapists' => $businessCardTherapists,
            'therapistReviews' => $therapistReviews,
        ]);
    }

    /**
     * @param $q
     * @return string
     */
    public function actionSearch($q)
    {
        $query = new Query(['options' => ['q' => $q]]);
        $query->from('treatfield');

        $provider = new ActiveDataProvider([
            'query' => $query,
            'pagination' => [
                'pageSize' => 20,
            ]
        ]);

        return $this->render('search', [
            'provider' => $provider,
            'q' => $q,
        ]);
    }

    /**
     * Set cookies that hide mailchimp popup
     */
    public function actionSubscribeSuccess()
    {
        if (\Yii::$app->request->isPost) {
            $hideTime = 259200; //3 days
        } else {
            //user has already subscribed
            $hideTime = 15552000; //180 days
        }
        Yii::$app->response->cookies->add(new Cookie([
            'name' => 'hideMailchimp',
            'value' => true,
            'expire' => time() + $hideTime,
            'domain' => 'www.treatfield.com' //https://stackoverflow.com/a/2345183
        ]));

        if (\Yii::$app->request->isGet) {
            \Yii::$app->response->redirect('/');
        }
    }

    /**
     * @return string
     */
    public function actionError()
    {
        $exception = Yii::$app->errorHandler->exception;

        if ($exception !== null) {
            return $this->render('error', [
                'exception' => $exception,
            ]);
        }
    }
}

frontend/views/site/_business_cards.php
<?php

use common\models\Therapist;

/** @var Therapist[] $therapists */

?>

<section class="section-image section-business parallax">
    <div class="section-business-content">
        <div class="container">
            <div class="row">
                <div class="col-sm-12">
                    <div id="carousel-business-generic" class="carousel slide" data-ride="carousel">

                        <h3 hidden>Визитки терепавтов онлайн-платформы Тритфилд</h3>

                        <div class="carousel-inner owl-carousel owl-theme" role="listbox">
                            <?php foreach ($therapists as $i => $therapist): ?>
                                <div class="item <?= ($i === 0) ? 'active' : ''; ?>">
                                    <div class="col-md-12 youtube-wrapper">
                                        <div class="youtube">
                                            <a href="#" data-video-url="<?= $therapist->business_card_url ?>?autoplay=1"
                                               data-target="#video-modal">
                                                <div class="play-button"></div>
                                                <?php $embed = explode('/', $therapist->business_card_url); ?>
                                                <img src="https://img.youtube.com/vi/<?= end($embed) ?>/hqdefault.jpg" alt="<?= $therapist->additional->business_card_image_alt ?>">
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            <?php endforeach; ?>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>

    <a href="/field?tag=vizitka" class="btn-orange">Все визитки</a>

</section>

frontend/views/site/_mailchipm.php
<div id="mc_embed_signup" class="mc_embed_signup_landing">
    <form action="//treatfield.us15.list-manage.com/subscribe/post?u=164f88a778c7108c77893020b&amp;id=5acfdd87e6" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
        <div id="mc_embed_signup_scroll">
            <div class="container">
                    <h1 class="section-title">Рассылка</h1>
                    <span><?= Yii::t('main', 'Subscribe to the newsletter not to miss nothing') ?></span>
                    <input type="email" value="" name="EMAIL" class="email form-control" id="mce-EMAIL" required/>
                    <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
                    <div style="position: absolute; left: -5000px;" aria-hidden="true">
                        <input type="text" name="b_164f88a778c7108c77893020b_5acfdd87e6" tabindex="-1" value=""/>
                    </div>
                    <input type="submit" value="<?= Yii::t('main', 'Subscribe')?>" name="subscribe" id="mc-embedded-subscribe" class="btn-link subscribe-btn"/>

                <div class="scroll-to-top">
                    <a href="#top">
                        <i class="fa fa-angle-up" aria-hidden="true"></i>
                    </a>
                </div>
            </div>
        </div>
    </form>
</div>

frontend/views/site/_mailchipm_absolute.php
<?php

use frontend\components\TooltipHelper;

$hideMailchimp = !Yii::$app->request->cookies->getValue('hideMailchimp', false);
$showTooltips = Yii::$app->tooltip->step < TooltipHelper::STEP_5;

?>

<?php if (!$hideMailchimp && !$showTooltips): ?>
    <style>
        #mc_embed_signup {
            background: #f5f5f5;
            font: 14px Helvetica, Arial, sans-serif;
            width: 100%;
            padding: 10px 80px;
            position: fixed;
            bottom: -2px;
            left: 0;
            z-index: 9990;
            display: none;
        }

        #mc_embed_signup #sub-title, #mobile_mc_embed_signup #sub-title {
            color: rgb(109, 193, 244);
            font-size: 18px;
        }

        #mc_embed_signup .subscribe-btn {
            margin: -2px 0;
            padding: 6px 19px;
        }

        #mc_embed_signup input.email {
            width: 40%;
            margin-right: 15px;
            margin-left: 15px;
        }

        #mc_embed_signup .close {
            margin-right: -60px;
        }

        .wait-for-popup .close {
            float: right;
            font-size: 45px;
            line-height: 0.5;
            font-weight: normal;
        }

        .wait-for-popup .close:hover, .wait-for-popup .close:focus {
            color: #000;
            text-decoration: none;
            cursor: pointer;
            filter: alpha(opacity=50);
            opacity: .5;
        }

        .wait-for-popup .close:focus {
            outline: 0 !important;
        }

        /** MOBILE **/
        #mobile_mc_embed_signup {
            height: 50px;
            width: 100%;
            text-align: center;
            padding-top: 6px;
            display: none;
            cursor: pointer;
            position: fixed;
            bottom: -2px;
            left: 0;
            z-index: 9990;
            background: #f4f4f4;
        }

        #mobile_mc_embed_signup img {
            position: absolute;
            height: 85px;
            left: -10px;
            bottom: -5px;
        }

        #mobile_mc_embed_signup > span {
            font-size: 18px;
            text-align: center;
            display: block;
            padding-top: 5px;
        }

        #mobile_mc_embed_signup .close {
            display: block;
            position: absolute;
            right: 15px;
            top: 12px;
        }

        #subscribe-modal .modal-body .page-btn {
            margin-left: auto;
            margin-right: auto;
            display: block;
        }

        @media (max-width: 1245px) {
            #mc_embed_signup span {
                display: block;
                margin-bottom: 5px;
                width: 100%;
            }
        }

        @media (max-width: 1024px) {
            #mc_embed_signup input.email {
                width: 50%;
            }
        }

        @media (max-width: 320px) {
            #mobile_mc_embed_signup > span {
                font-size: 15px;
            }
        }

    </style>

    <div id="mc_embed_signup" class="wait-for-popup">
        <form action="//treatfield.us15.list-manage.com/subscribe/post?u=164f88a778c7108c77893020b&amp;id=5acfdd87e6" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
            <div id="mc_embed_signup_scroll">
                <div class="row">
                    <span id="sub-title"><?= Yii::t('main', 'Подпишитесь на рассылку, чтобы ничего не упустить') ?></span>
                    <input type="email" value="" name="EMAIL" class="email form-control" id="mce-EMAIL" placeholder="example@mail.com" required/>
                    <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
                    <div style="position: absolute; left: -5000px;" aria-hidden="true">
                        <input type="text" name="b_164f88a778c7108c77893020b_5acfdd87e6" tabindex="-1" value=""/>
                    </div>
                    <input type="submit" value="<?= Yii::t('main', 'Subscribe')?>" name="subscribe" id="mc-embedded-subscribe" class="page-btn small-page-btn subscribe-btn"/>
                    <button type="button" class="close" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            </div>
        </form>
    </div>

    <div id="mobile_mc_embed_signup" class="wait-for-popup" data-toggle="modal" data-target="#subscribe-modal">
        <img src="/img/subscribe-man.png"/>
        <span><?= Yii::t('main', 'Подпишитесь на рассылку') ?></span>
        <button type="button" class="close" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>

    <!-- Modal -->
    <div id="subscribe-modal" class="modal fade standart-modal" role="dialog" aria-hidden="true" aria-labelledby="myModalLabel">
        <div class="modal-dialog">
            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>
                <div class="modal-body">
                    <form action="//treatfield.us15.list-manage.com/subscribe/post?u=164f88a778c7108c77893020b&amp;id=5acfdd87e6" method="post" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
                        <div class="row">
                            <h3><?= Yii::t('main', 'Subscribe to the newsletter not to miss nothing') ?></h3>
                            <input type="email" value="" name="EMAIL" class="email form-control" id="mce-EMAIL" placeholder="example@mail.com" required/>
                            <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
                            <div style="position: absolute; left: -5000px;" aria-hidden="true">
                                <input type="text" name="b_164f88a778c7108c77893020b_5acfdd87e6" tabindex="-1" value=""/>
                            </div>
                            <input type="submit" value="<?= Yii::t('main', 'Subscribe')?>" name="subscribe" class="page-btn small-page-btn subscribe-btn"/>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

<?php endif; ?>

frontend/views/site/_reviews.php
<?php

use common\models\TherapistReview;
use frontend\components\DeviceManager;

/** @var TherapistReview[] $therapistReviews */

$reviewTextLimit = DeviceManager::isMobile() ? 200 : 500;

?>

<section class="reviews">
    <div class="container">

        <h3 class="section-title">Отзывы пользователей</h3>

        <div id="reviews" class="carousel slide" data-ride="carousel">
            <div class="carousel-inner" role="listbox">
                <?php foreach ($therapistReviews as $index => $review): ?>
                    <div class="item <?= $index === 0 ? 'active' : '' ?>">
                        <div class="rev-text">
                            <?php
                                $textLen = mb_strlen($review->text, 'utf-8');
                                $offset = $reviewTextLimit < $textLen ? $reviewTextLimit : $textLen;
                                $pivot = mb_strpos($review->text, ' ', $offset - 1, 'utf-8');
                                $pivot = !$pivot ? $reviewTextLimit : $pivot;
                            ?>
                            <?= mb_substr($review->text, 0, $pivot, 'utf-8') ?>
                            <?php if ($textLen > $pivot): ?>
                                <span class="full-text">
                                    <?= mb_substr($review->text, $pivot, null, 'utf-8') ?>
                                </span>
                                &mdash; <span class="read-more">читать весь</span>
                            <?php endif; ?>
                        </div>
                        <div class="comentator">
                            <?= $review->name ?> o
                            <a href="/therapist/<?= $review->therapist->alias ?>" class="doctor">
                                <?= $review->therapist->name ?>
                            </a>
                        </div>
                    </div>
                <?php endforeach; ?>
            </div>

            <a class="left carousel-control" href="#reviews" role="button" data-slide="prev">
                <!--span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span-->
                <span aria-hidden="true">
                    <span class="control-arrow"></span>
                </span>
                <span class="sr-only">
                    <?= Yii::t('main', 'Previous'); ?>
                </span>
            </a>

            <a class="right carousel-control" href="#reviews" role="button" data-slide="next">
                <!--span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span-->
                <span aria-hidden="true">
                    <span class="control-arrow"></span>
                </span>
                <span class="sr-only">
                    <?= Yii::t('main', 'Next'); ?>
                </span>
            </a>

            <!--ol class="carousel-indicators">
                <?php foreach ($therapistReviews as $index => $review): ?>
                    <li data-target="#reviews" data-slide-to="<?= $index ?>"
                        class="<?= $index === 0 ? 'active' : '' ?>"></li>
                <?php endforeach; ?>
            </ol-->
        </div>

        <!--div class="btn-container">
            <a href="/therapists/reviews" class="btn-orange">Все отзывы</a>
        </div-->

    </div>
</section>

frontend/views/site/_search_item.php
<?php

use yii\helpers\StringHelper;

?>

<div class="col-lg-12 search-item">

    <a class="search-item-link" href="<?= $model['url'] ?>">
        <h3 class="search-item-title">
            <?php if($type == 'therapist'): ?>
            <i class="fa fa-user" aria-hidden="true"></i>
            <?php else: ?>
            <i class="fa fa-newspaper-o" aria-hidden="true"></i>
            <?php endif; ?>
            <?= $model['title'] ?>            
        </h3>
    </a>

    <div class="search-item-content">
        <?= StringHelper::truncateWords(strip_tags($model['content']), 50) ?>
    </div>

</div>

frontend/views/site/error.php
<?php

use frontend\assets\AppAsset;
use yii\web\NotFoundHttpException;

AppAsset::register($this);

$this->title = Yii::t('main', 'Error');

/** @var \yii\base\Exception $exception */

?>

<div class="content-page">
    <div class="container">
        <div class="page-inner">
            <?php if ($exception instanceof NotFoundHttpException || $exception->getCode() === 404): ?>
                <h3><?= Yii::t('main', 'Looks like this page does not exist') ?></h3>
            <?php else: ?>
                <h3><?= Yii::t('main', 'Looks like something went wrong on our end') ?></h3>
            <?php endif; ?>
            <p>
                <?= Yii::t('main', '{0}Contact{1} us to help solve this issue.', [
                    '<a data-target="#modal" href="/contact">',
                    '</a>'
                ]); ?>
            </p>
            <div class="row">
                <div class="col-md-4 col-sm-4 col-md-offset-4 col-sm-offset-4">
                    <img src="/img/error.png"
                         style="height: 100%; width: 100%; object-fit: contain;"
                         alt="<?= Yii::t('main', 'Looks like something went wrong on our end') ?>"/>
                </div>
            </div>
        </div>
    </div>
</div>